version: '3.7'

services:
  db:
    image: influxdb:1.7-alpine
    environment:
      INFLUXDB_DB: "bathroom"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - 9000:8000
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.production"
    depends_on:
      - db
    volumes:
      - /tmp/bathroom-api-static/:/code/staticfiles/
  redis:
    image: redis:alpine
    restart: always
